apiVersion: v1
kind: Secret
metadata:
  name: velero-backup-notification-secrets
type: Opaque
stringData:
  slack_webhook: {{ .Values.slack.webhook | quote }}
  slack_channel: {{ .Values.slack.channel | quote }}
